name: "Build Docker Images"

on:
  create: # Branch (so that the Docker image tags exist for a new branch when pushed)
          # even if nothing on 'paths' below is changed.
    branches:
      - '**'

  push:
    paths:
      - "qhub/template/{{ cookiecutter.repo_directory }}/image/**"
      - ".github/workflows/image.yaml"

    branches: # Only on paths above
      - '**'

    tags: # Always, regardless of paths above
      - '*'

jobs:
  base-image:
    name: 'Build Base Docker Images'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BASE:
          - centos-base
          - ubuntu-base
    outputs:
      base-image-tag: ${{ steps.meta.outputs.tags }}
    steps:
      - name: 'Checkout Infrastructure'
        uses: actions/checkout@main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          # list of Docker images to use as base name for tags
          images: |
            "quansight/qhub-${{ matrix.BASE }}"
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Build docker
        uses: docker/build-push-action@v2
        with:
          context: "./qhub/template/{{ cookiecutter.repo_directory }}/image/base"
          file: "./qhub/template/{{ cookiecutter.repo_directory }}/image/base/Dockerfile.${{ matrix.BASE }}"
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}

  matrix-build:
    needs: base-image
    strategy:
      fail-fast: false
      matrix:
        include:
          - IMAGE: jupyterlab
          - IMAGE: jupyterhub
          - IMAGE: dask-worker
          - IMAGE: dask-gateway
          - IMAGE: conda-store
          # build non-default, centos image
          - IMAGE: jupyterlab
            DISTRO: centos
          - IMAGE: dask-worker
            DISTRO: centos
    name: ${{ matrix.IMAGE }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Infrastructure'
        uses: actions/checkout@main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          # list of Docker images to use as base name for tags
          images: |
            "quansight/qhub-${{ matrix.IMAGE }}"
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Build docker
        uses: docker/build-push-action@v2
        with:
          context: "./qhub/template/{{ cookiecutter.repo_directory }}/image"
          file: "./qhub/template/{{ cookiecutter.repo_directory }}/image/Dockerfile.${{ matrix.IMAGE }}"
          build-args: |
            DISTRO=${{ matrix.DISTRO }}
            BASE_IMAGE=${{ needs.base-image.outputs.base-image-tag }}
          tags: ${{ format('{0}{1}', steps.meta.outputs.tags, matrix.DISTRO) }}
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
